# -*- coding: utf-8 -*-
"""week-14

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i1lXv9sDZPFWZd1xDNoNLchQPtGYfnlr

**OBJECTIVE 1: DATA COLLECTION**

CELL 1 — MOUNT GOOGLE DRIVE
"""

from google.colab import drive
drive.mount('/content/drive')

"""**CELL 2 — IMPORT REQUIRED LIBRARIES**"""

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

import plotly.express as px
import plotly.graph_objects as go

import warnings
warnings.filterwarnings('ignore')

"""**CELL 3 — LOAD DATASET FROM GOOGLE DRIVE**"""

df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/credit_card_fraud_synthetic.csv')
print("Dataset Loaded Successfully")

"""**CELL 4 — DISPLAY FIRST 5 ROWS**"""

df.head()

"""**CELL 5 — CHECK DATASET SHAPE**"""

print("Rows :", df.shape[0])
print("Columns :", df.shape[1])

"""**CELL 6 — CHECK COLUMN NAMES**"""

df.columns

"""**OBJECTIVE 2: DATA CLEANING & PREPROCESSING**

**CELL 7 — CHECK MISSING VALUES**
"""

df.isnull().sum()

"""**CELL 8 — REMOVE DUPLICATES**"""

df = df.drop_duplicates()

print("Duplicates Removed")
print("New Shape :", df.shape)

"""**CELL 9 — CHECK DATA TYPES**"""

df.dtypes

"""**CELL 10 — FILL NULL VALUES IF PRESENT**"""

df = df.fillna(df.mean(numeric_only=True))
print("Missing Values Handled")

"""**CELL 11 — BASIC DATA INFORMATION**"""

df.info()

"""**OBJECTIVE 3: DESCRIPTIVE STATISTICS**

**CELL 12 — DESCRIPTIVE STATISTICS**
"""

df.describe()

"""**CELL 13 — AVERAGE TRANSACTION AMOUNT**"""

avg_amount = df['Amount'].mean()

print("Average Transaction Amount :", avg_amount)

"""**CELL 14 — FRAUD VS NORMAL COUNT**"""

fraud_count = df['Class'].value_counts()

print(fraud_count)

"""**CELL 15 — FRAUD PERCENTAGE**"""

fraud_percent = (df['Class'].sum()/len(df))*100

print("Fraud Percentage :", fraud_percent)

"""**OBJECTIVE 4: FRAUD BEHAVIOR ANALYSIS**

**CELL 16 — FRAUD VS NORMAL TRANSACTION ANALYSIS**
"""

fraud = df[df['Class']==1]
normal = df[df['Class']==0]

print("Fraud Transactions :", len(fraud))
print("Normal Transactions :", len(normal))

"""**CELL 17 — FRAUD TRANSACTION STATISTICS**"""

fraud['Amount'].describe()

"""**CELL 18 — NORMAL TRANSACTION STATISTICS**"""

normal['Amount'].describe()

"""**OBJECTIVE 5: GROUP-BASED ANALYSIS**

**CELL 19 — AMOUNT VS FRAUD**
"""

df.groupby('Class')['Amount'].mean()

"""**CELL 20 — TIME VS FRAUD**"""

df.groupby('Class')['Time'].mean()

"""**CELL 21 — FEATURE PATTERN ANALYSIS**"""

df.groupby('Class').mean()

"""**OBJECTIVE 6: RELATIONSHIP ANALYSIS**

**CELL 22 — CORRELATION MATRIX**
"""

correlation = df.corr()

correlation

"""**CELL 23 — TOP CORRELATED FEATURES WITH CLASS**"""

correlation['Class'].sort_values(ascending=False)

"""**OBJECTIVE 7: DATA VISUALIZATION**

**CELL 24 — FRAUD DISTRIBUTION BAR CHART**
"""

plt.figure(figsize=(6,5))

sns.countplot(x='Class', data=df)

plt.title('Fraud Distribution')
plt.show()

"""**CELL 25 — TRANSACTION AMOUNT HISTOGRAM**"""

plt.figure(figsize=(8,5))

plt.hist(df['Amount'], bins=50)

plt.title('Transaction Amount Distribution')
plt.xlabel('Amount')
plt.ylabel('Frequency')

plt.show()

"""**CELL 26 — SCATTER PLOT**"""

plt.figure(figsize=(8,5))

plt.scatter(df['Time'], df['Amount'])

plt.title('Time vs Amount')
plt.xlabel('Time')
plt.ylabel('Amount')

plt.show()

"""**CELL 27 — BOXPLOT FOR OUTLIER DETECTION**"""

plt.figure(figsize=(8,5))

sns.boxplot(x='Class', y='Amount', data=df)

plt.title('Fraud vs Amount')

plt.show()

"""**CELL 28 — HEATMAP**"""

plt.figure(figsize=(15,10))

sns.heatmap(df.corr(), cmap='coolwarm')

plt.title('Correlation Heatmap')

plt.show()

"""**OBJECTIVE 8: RISK ANALYSIS**

**CELL 29 — CREATE RISK LEVELS**
"""

def risk_category(amount):

    if amount < 100:
        return 'Low Risk'

    elif amount < 1000:
        return 'Medium Risk'

    else:
        return 'High Risk'

df['Risk_Level'] = df['Amount'].apply(risk_category)

df[['Amount','Risk_Level']].head()

"""**CELL 30 — RISK LEVEL COUNT**"""

df['Risk_Level'].value_counts()

"""**CELL 31 — RISK LEVEL VISUALIZATION**"""

plt.figure(figsize=(7,5))

sns.countplot(x='Risk_Level', data=df)

plt.title('Risk Level Distribution')

plt.show()

"""**OBJECTIVE 9: PREDICTIVE MODELING (LINEAR REGRESSION)**

**CELL 32 — DEFINE X AND Y VARIABLES**
"""

X = df[['Time']]
y = df['Amount']

"""**CELL 33 — TRAIN TEST SPLIT**"""

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

"""**CELL 34 — BUILD LINEAR REGRESSION MODEL**"""

model = LinearRegression()

"""**CELL 35 — TRAIN MODEL**"""

model.fit(X_train, y_train)

print("Model Training Completed")

"""**CELL 36 — MAKE PREDICTIONS**"""

y_pred = model.predict(X_test)

print(y_pred[:10])

"""**OBJECTIVE 10: MODEL EVALUATION**

**CELL 37 — R2 SCORE**
"""

r2 = r2_score(y_test, y_pred)

print("R2 Score :", r2)

"""**CELL 38 — ERROR METRICS**"""

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)

print("Mean Absolute Error :", mae)
print("Mean Squared Error :", mse)

"""**CELL 39 — RESIDUAL ANALYSIS**"""

residuals = y_test - y_pred

plt.figure(figsize=(8,5))

plt.scatter(y_pred, residuals)

plt.axhline(y=0)

plt.title('Residual Analysis')
plt.xlabel('Predicted Values')
plt.ylabel('Residuals')

plt.show()

"""**OBJECTIVE 11: DASHBOARD CREATION**

**CELL 40 — INTERACTIVE FRAUD DISTRIBUTION**
"""

fig = px.histogram(
    df,
    x='Class',
    title='Fraud Distribution'
)

fig.show()

"""**CELL 41 — INTERACTIVE AMOUNT TREND**"""

fig = px.line(
    df.head(1000),
    x='Time',
    y='Amount',
    title='Transaction Amount Trend'
)

fig.show()

"""**CELL 42 — INTERACTIVE FRAUD COMPARISON**"""

fig = px.box(
    df,
    x='Class',
    y='Amount',
    title='Fraud vs Amount'
)

fig.show()

"""**CELL 43 — INTERACTIVE CORRELATION HEATMAP**"""

fig = px.imshow(
    correlation,
    title='Correlation Heatmap'
)

fig.show()

"""**CELL 44 — RISK LEVEL DASHBOARD**"""

fig = px.pie(
    df,
    names='Risk_Level',
    title='Risk Level Distribution'
)

fig.show()